version: "3.8"

services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - shared_database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "example"

volumes:
  shared_database:
